### ISSUE TITLE
remark-code font-size too large to be useful

### ISSUE THREAD

**Issue by matthewfeickert** [glouppe/talk-template#4]
Hi @glouppe. I've noticed recently that when I want to use a code block in a presentation that I need to adjust the following `font-size`

https://github.com/glouppe/talk-template/blob/a7e727d29015945a49a51542615e99e06a68e639/assets/style.css#L107-L109

to be 

```
.remark-code {
    font-size: 1em;
}
```

or around there to have any amount of code fit on the slide given how big `8em` is. As an example, adding the following slide with `8em`

```
---
# Test

~~~
$ pyhf cls example.json
{
    "CLs_exp": [
        0.07807427911686152,
        0.17472571775474582,
        0.35998495263681274,
        0.6343568235898907,
        0.8809947004472013
    ],
    "CLs_obs": 0.3599845631401913
}
~~~
```

produces the below

![too_big](https://user-images.githubusercontent.com/5142394/66397690-a3b2ed00-e9dc-11e9-967d-71b88516313b.png)

I've changed this in my fork, but I'm curious when this size change was added in 42c576bc8c4a457602eecadef3a199b475310a31 what the use case was.

**Comment by glouppe** [comment]
Closing, as this is fixed.
